version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: app.localhost
      VIRTUAL_PORT: 3000
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
  varnish:
    image: eeacms/varnish
    ports:
      - 3000:6081
    environment:
      BACKENDS: proxy
      BACKENDS_PROBE_INTERVAL: 5s
      BACKENDS_PROBE_REQUEST: 'GET / HTTP/1.1|Host: app.localhost|Connection: close|User-Agent: Varnish Health Probe'
      BACKENDS_PROBE_REQUEST_DELIMITER: '|'
    depends_on:
      - proxy
